ringerz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView # Needed to redirect "/"" to "/schedule".
from schedule.views import userSignUpView # Import signup form

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', userSignUpView, name='user-signup'),
    path('schedule/', include('schedule.urls')), # Includes URLs defined in 'schedule/urls.py'.
    path('', RedirectView.as_view(url='schedule/', permanent=True)), # Redirects "/" to "schedule/".
    path('accounts/', include('django.contrib.auth.urls')) # For user authentication
]

schedule/urls.py
from django.urls import path
from django.conf.urls import url
from . import views # Import custom views.

urlpatterns = [
    path('', views.EventListView.as_view(), name='event-list'),
    path('event/<int:pk>/', views.EventDetailView.as_view(), name='event-detail'),
    path('newevent/', views.NewEventCreateView.as_view(), name='event-create'),
    path('slot/<uuid:pk>/join/', views.SlotJoinView, name='slot-join'),
    path('slot/<uuid:pk>/leave/', views.SlotRemoveView, name='slot-remove'),
    path('slot/<uuid:pk>/delete/', views.EventSlotDeleteView, name='slot-delete'),
    path('event/<int:pk>/eventupdate/', views.EventUpdateView, name='event-update'),
    path('event/<int:pk>/statusupdate/', views.EventStatusUpdateView, name='event-status-update'),
    path('event/<int:pk>/slotsupdate/', views.EventSlotsUpdateView, name='event-slots-update'),
    path('myevents/', views.MyEventsView, name='my-events')
]

schedule/models.py
import datetime

from django.db import models # Default

from django.urls import reverse # Used to generate URLs by reversing the URL patterns.
from django.contrib.auth.models import User # Used to assign 'Users' to models fields.
import uuid # Requred for Slot

# Event class.
# These are the events users create when they need subs.
# Subs than accept an open 'slot'
class Event(models.Model):
	title			= models.CharField(max_length=20) # The name the user assigns to the event.
	sport			= models.CharField(max_length=20) # Will eventually make this a drop down but need to learn how to specify 'other'.
	organizer		= models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
	# date			= models.DateField()
	# time			= models.TimeField()
	datetime		= models.DateTimeField(auto_now=False, auto_now_add=False)
	location		= models.CharField(max_length=100)
	details			= models.TextField(max_length=1000, help_text="Enter some event details", null=True, blank=True)
	total_slots		= models.IntegerField()

	EVENT_STATUS	= (
		('o', 'Upcoming'),
		('f', 'Filled'),
		('c', 'Cancelled'),
		('d', 'Done')
	)

	status			= models.CharField(max_length=1, choices=EVENT_STATUS, default='o')

	def __str__(self):
		# String for representing the Model object.
		return f'{self.title}'

	def get_absolute_url(self):
		# Returns the url to access a detail record for this book.
		return reverse('event-detail', args=[str(self.id)])

	# Save override to create event 'slots' when the Event is created.
	# The number of Slot instances created is defined by the value in the 'total_slots' field.
	def save(self, *args, **kwargs):
		created = not self.pk
		super().save(*args, **kwargs)
		if created:
			for slot in range(self.total_slots):
				Slot.objects.create(event=self)

# Slot class
# These are the available positions for each event (i.e. how many subs are needed).
# Slots should be automatically created when an event is created.
# The number of slots created is defined by the 'total_slots' field in the Event class.
# The 'event' field should then be autofilled with the 'id' of the event that created the slot.
# The 'player' field is then filled in with the 'user' who accepted the slot.
class Slot(models.Model):
	id 		= models.UUIDField(primary_key=True, default=uuid.uuid4)
	event 	= models.ForeignKey('Event', on_delete=models.SET_NULL, null=True, blank=True)
	player 	= models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

	def __str__(self):
		# String for representing the Model object.
		return f'{self.id}'

schedule/views.py
import datetime
from django.utils import timezone
import pytz

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Event, Slot # Import models
from django.views import generic # Import the generic views to build the custom views from.
from django.views.generic.edit import CreateView, UpdateView # Specific import for creating and editting an event.
from django.contrib.auth.models import User # To get user information.
from django.db.models import Q # For search

from .forms import SignUpForm, EventCreateForm, EventUpdateForm # Import custom forms.

# Needed to check if users are authenticated in order to create new events and accept slots.
from django.contrib.auth.mixins import LoginRequiredMixin

# For new user sign up
from django.contrib.auth import login, authenticate

# List of Events (also the Home view when the user goes to '/')
class EventListView(generic.ListView):
	model = Event

	# Queryset is used for 'search'.
	# If there is no query variable, the whole list of 'open' events is returned.
	# If there is a query variable, the list is filtered through the 'title' and 'sport' fields.
	def get_queryset(self):
		query = self.request.GET.get('q')
		if query:
			return Event.objects.filter(Q(title__icontains=query) | Q(sport__icontains=query))
		else:
			return Event.objects.filter(Q(status='o') | Q(status='f'))

# Event details view so users can see all of the event details
class EventDetailView(generic.DetailView):
	model = Event

# Create a new event.
class NewEventCreateView(LoginRequiredMixin, CreateView):
	model = Event
	# fields = ['title', 'sport', 'date', 'time', 'location', 'details', 'total_slots']
	form_class = EventCreateForm

	# 'form_valid' override to save current user to the Event 'organizer' field on form submission.
	def form_valid(self, form):
		form.instance.organizer = self.request.user
		return super().form_valid(form)

# Edit an event.
# Simple form to edit an event.
# Form, however, cannot be used to update slot number.
# Separate view is required to update slots.
# View also prevents anyone other than they event 'organizer' from editting the event.
@login_required
def EventUpdateView(request, pk):
	event = get_object_or_404(Event, pk=pk)

	if request.user == event.organizer:
		if request.method == 'POST':
			form = EventUpdateForm(request.POST, instance=event)
			if form.is_valid():
				form.save()
				return redirect(event.get_absolute_url())
		if request.method == 'GET':
			form = EventUpdateForm(instance=event)
		context = {
			'form': form,
			'event': event
		}
		return render(request, 'schedule/event_update_form.html', context)
	else:
		return render(request, 'schedule/blocks/event_update_block.html', {})

# Update the Status of an Event (cancel or re-open)
# When the view is loaded, depending on the event status (i.e. event.status) the user is prompted to cancel or reopen the event
# On the post, the status is set to either 'c' or 'o' depending on the previous state.
# View also blocks anyone who is not the event organizer from changing the status.
@login_required
def EventStatusUpdateView(request, pk):
	event = get_object_or_404(Event, pk=pk)

	if request.user == event.organizer:
		if request.method == 'POST':
			if event.status == 'o':
				event.status = 'c'
			elif event.status =='c':
				event.status = 'o'
			event.save()
			return redirect('event-list')
		if request.method == 'GET':
			return (render(request, 'schedule/event_status_update.html', {'event': event}))
	else:
		return (render(request, 'schedule/blocks/event_cancel_block.html', {}))


# View for player to confirm they want to join that event by accepting the Slot.
# Once the player confirms the acceptance, the Slot 'player' field is populated by the logged in user.
# View also blocks event organizer from joining one of the slots.
# View also blocks someone who has reserved a slot from taking another one.
@login_required
def SlotJoinView(request, pk):
	slot = get_object_or_404(Slot, pk=pk)
	queryset = Slot.objects.filter(event=slot.event)
	
	# Verify the slot status is 'open'. You cannot join as slot for an event that is 'filled', 'cancelled' or 'done'.
	if slot.event.status == 'o':

		# Verify slot is not taken (i.e slot.player has a value and is not null).
		# If the slot is occupied, the 'join' is blocked.
		if slot.player != None:
			return render(request, 'schedule/blocks/slot_join_block.html', {})

		# If slot.player is available (i.e. slot.player == None), check to make sure the user is not the event organizer.
		# If the user is the event organizer, the 'join' is blocked.
		if request.user == slot.event.organizer:
			return render(request, 'schedule/blocks/slot_join_block.html', {})

		# Go through each Slot associated to the event and check the assigned player.
		# If the current user appears in any other slot, then the loop exits and the 'join' is blocked.
		for query in queryset:
			if query.player != None:
				if query.player == request.user:
					return render(request, 'schedule/blocks/slot_join_block.html', {})

		# Once block checks have been made, the POST or GET is processed.
		# POST - current user is assigned to the slot instance. User is redirected to event details page.
		# GET - 'confirm join' form is rendered and the current user can confirm they want to join the event (submit trigger the POST).
		if request.method == 'POST':
			slot.player = request.user
			slot.save()
			# Now check to see if all slots are filled. If so, event status becomes 'Filled'.
			if slot.event.status == 'o':
				for idx, query in enumerate(queryset):
					if query == slot:
						if (idx+1) % query.event.total_slots == 0:
							slot.event.status = 'f'
					if query.player == None:
						break
					else:
						if (idx+1) % query.event.total_slots == 0:
							slot.event.status = 'f'
				slot.event.save()
			return redirect(slot.event.get_absolute_url())
		if request.method=='GET':
			return (render(request, 'schedule/slot_join.html', {'slot':slot}))
	else:
		return render(request, 'schedule/blocks/slot_join_block.html', {})

# View for player to confirm they want to leave an event after they have joined.
# Once the player confirms they want to leave, the Slot 'player' field is set to none.
# View also blocks anyone other than the slot.player from removing the player.
@login_required
def SlotRemoveView(request, pk):
	slot = get_object_or_404(Slot, pk=pk)
	
	# Check if the current user is the player assigned to the slot.
	# If not, the 'remove' is blocked.
	if request.user == slot.player:
		if request.method == 'POST':
			slot.player = None
			slot.save()
			# Only reopened events that are filled.
			# If an event is 'cancelled' or 'done', leaving the event does not change the event status.
			if slot.event.status == 'f':
				slot.event.status = 'o'
				slot.event.save()
			return redirect('event-detail', pk=slot.event.id)
		if request.method =='GET':
			return (render(request, 'schedule/slot_remove.html', {'slot': slot}))
	else:
		return (render(request, 'schedule/blocks/slot_remove_block.html', {}))

# View My Events
# View for the user to see the events they are the 'organizer' for
# View also to see the events where the user occupies one of the 'slots' (i.e. slot.player == user)
@login_required
def MyEventsView(request):

	events = Event.objects.filter(organizer=request.user).order_by('datetime') # Get all the events the user is the 'organizer'.
	slots = Slot.objects.filter(player=request.user) # Get all the slots the user is the 'player'.

	context = {
		'events': events,
		'slots': slots
	}

	return render(request, "schedule/myevents.html", context)

# View to see all the slots for an event and add/remove slots.
# Hitting add slot is a post which creates another slot with the slot.event = the current event.
# The number of slots associated to that event are counted and the total_slots are updated to that count.
# Each existing slot has a link to another view to confirm their deletion.
# View also blocks anyone other than the event 'organizer' from adding/removing slots.
@login_required
def EventSlotsUpdateView(request, pk):
	event = get_object_or_404(Event, pk=pk)

	if request.user == event.organizer:
		context = {
			'event': event
		}
		if request.method == 'POST':
			Slot.objects.create(event=event)
			event.total_slots = Slot.objects.filter(event=event).count() # Count new amount of slots for that event and update total_slots to that number.
			if event.status == 'f':
				event.status = 'o'
			event.save()
			return (render(request,"schedule/edit_slots.html", context))
		if request.method == 'GET':
			return (render(request,"schedule/edit_slots.html", context))
	else:
		return (render(request, 'schedule/blocks/event_update_block.html', {}))

# View to delete a slot
# User hits confirm to delete the slot entry (slot instance is completely deleted).
# The number of slots associated to that event are counted and the total_slots are updated to that count.
# User is returned to EventSlotsUpdateView.
# View also blocks anyone other than the event 'organizer' from deleting the slot.
@login_required
def EventSlotDeleteView(request, pk):
	slot = get_object_or_404(Slot, pk=pk)
	event = slot.event
	queryset = Slot.objects.filter(event=slot.event)

	if queryset.count() == 1:
		return redirect('event-slots-update', pk=event.id)

	if request.user == slot.event.organizer:
		if request.method == 'POST':
			# Block 'delete' if there is only one slot.
			if queryset.count() == 1:
				return redirect('event-slots-update', pk=event.id)
				# return (render(request, 'schedule/blocks/event_update_block.html', {}))
			slot.delete()
			# Count remaining slots for that event and update total_slots to that number.
			event.total_slots = queryset.count() 

schedule/templates/schedule/edit_slots.html
{% extends "base.html" %}

{% block content %}
<div class="container my-2">
	<div class="row">
		<div class="col">
			<h5>Positions for {{ event }}</h5>
		</div>
	</div>
	<table class="table">
		<tbody>
			{% for slot in event.slot_set.all %}
			<tr>
				<th scope="row" style="width: 60%">
					{{ slot.player }}
				</th>
				{% if event.total_slots != 1 %}
					<td style="width: 40%">
						<a href="{% url 'slot-delete' slot.pk %}" class="btn btn-primary btn-block">Remove</a>
					</td>
				{% elif error == True %}
					<td style="width: 40%">
						You cannot delte this position. You must have at least one position.
						<!-- <a href="{% url 'slot-delete' slot.pk %}" class="btn btn-primary btn-block">Remove</a> -->
					</td>
				{% endif %}
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
<div class="container my-2">
	<div class="row">
		<div class="col">
			<form action="" method="POST">
				{% csrf_token %}
				<input type="submit" value="Add Position" class="btn btn-primary btn-block">
			</form>
		</div>
	</div>
	<div class="row my-2">
		<div class="col">
			<a href="{{ event.get_absolute_url }}" class="btn btn-secondary btn-block">Back To Event</a></p>
		</div>
	</div>
</div>
{% endblock%}

schedule/templates/schedule/event_detail.html
{% extends "base.html" %}

{% block content %}
	<!-- Container for event details -->
	<div class="container my-2">
		<div class="row">
			<div class="col-8">
				<h4>{{ event.title }}</h4>
			</div>
			<div class="col">
				<h5 class="{% if event.status == 'o' %}text-success{% elif event.status == 'c' %}text-danger{% else %}text-warning{% endif %}">{{ event.get_status_display }}</h5>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-8">
				<strong>Organizer: </strong>{{ event.organizer}}
			</div>
			<div class="col-sm">
				<strong>Activity: </strong>{{ event.sport}}
			</div>
		</div>
		<div class="row">
			<div class="col">
				<strong>Time: </strong>{{ event.datetime }}
			</div>
		</div>
		<div class="row">
			<div class="col">
				<strong>Location: </strong>{{ event.location }}
			</div>
		</div>
		<div class="row">
			<div class="col">
				<strong>Details: </strong>{{ event.details }}
			</div>
		</div>
		<div class="row">
			<div class="col">
				<strong>Players Needed:</strong> {{ event.total_slots }}
			</div>
		</div>
	</div>

	<!-- Container for slot details -->
	{% if user == event.organizer%}
		<div class="container my-3">
			<div class="row">
				<div class="col">
					<h5>Recruited Players</h5>
				</div>
			</div>
			<table class="table table-borderless">
				<tbody>
					{% for slot in event.slot_set.all %}
						<tr>
							<td class="text-center">{{ slot.player }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="container my-2">
			<div class="row">
				<div class="col">
					<a href="{% url 'event-update' event.pk %}" class="btn btn-primary btn-block">Edit Event Details</a>
				</div>
			</div>
			<div class="row my-2">
				<div class="col">
					<a href="{% url 'event-list' %}" class="btn btn-secondary btn-block">Go Back</a>
				</div>
			</div>
		</div>
	{% else %}
		<div class="container my-3">
			<div class="row">
				<div class="col">
					<h5>Recruited Players</h5>
				</div>
			</div>
			<table class="table table-borderless">
				<tbody>
					{% for slot in event.slot_set.all %}
						{% if slot.player != None %}
							{% if user == slot.player %}
								<tr class="text-center">
									<td>{{ slot.player }}</td>
									<td><a href="{% url 'slot-remove' slot.pk %}" class="float-center btn btn-primary">Leave Team</a></td>
								</tr>
							{% else %}
								<tr>
									<td class="text-center" colspan="2">{{ slot.player }}</td>
								</tr>
							{% endif %}
						{% else %}
							<tr>
								<td class="text-center" colspan="2">
									<a href="{% url 'slot-join' slot.pk %}" class="btn btn-success">Position Available</a>
								</td>
							</tr>
						{% endif %}
					{% endfor %}
				</tbody>
			</table>
		</div>
	{% endif %}
{% endblock %}

schedule/templates/schedule/event_form.html
{% extends "base.html" %}

{% block content %}
	
	{{ form.media }}

	<div class="container my-2">
		<div class="row">
			<div class="col">
				<h5>Create an Event</h5>
			</div>
		</div>
	</div>
	<div class="container">
		<form action="" method="post"> {% csrf_token %}
			{{ form.non_field_errors }}
			<div class="form-group">
				<label for="{{ form.title.id_for_label }}">Event Title<span class="req">*</span></label>
				{{ form.title }}
				{{ form.title.errors }}
			</div>
			<div class="form-group">
				<label for="{{ form.sport.id_for_label }}">Sport/Activity<span class="req">*</span></label>
				{{ form.sport }}
				{{ form.sport.errors }}
			</div>
			<div class="form-group">
					<label for="{{ form.datetime.id_for_label }}">Date<span class="req">*</span></label>
					{{ form.datetime }}
					{{ form.datetime.errors }}
			</div>
			<div class="form-group">
				<label for="{{ form.location.id_for_label }}">Location<span class="req">*</span></label>
				{{ form.location }}
				{{ form.location.errors }}
			</div>
			<div class="form-group">
				<label for="{{ form.details.id_for_label }}">Details</label>
				{{ form.details }}
				{{ form.details.errors }}
			</div>
			<div class="form-group">
				<label for="{{ form.total_slots.id_for_label }}">Players Needed<span class="req">*</span></label>
				{{ form.total_slots }}
				{{ form.total_slots.errors }}
			</div>
			<input type="submit" value="Submit" class="btn btn-primary btn-block my-2">
		</form>
		<a href="{% url 'event-list' %}" class="btn btn-secondary btn-block my-2">Cancel</a>
	</div>
{% endblock %}

schedule/templates/schedule/event_list.html
{% extends "base.html" %}

{% block content %}
	<div class="container my-2">
		<div class="row">
			<div class="col">
				<h2>Events in Your Area</h2>
			</div>
		</div>
	</div>
	<!-- Search bar -->
	<div class="container"> 
		<form action="" method="get">
			<div class="form-row align-items-center">
				<div class="col-sm col-md-8">
				  <input class="form-control textinput textInput" name="q" type="text" placeholder="{% if request.GET.q %}{{ request.GET.q }}{% else %}Search...{% endif %}">
				</div>
				<div class="col-sm col-md-4">
					<input type="submit" value="Search" class="btn btn-primary btn-block my-2">
				</div>
			</div>
		</form>
		{% if request.GET.q %}
		<div class="row">
			<div class="col-xs-4">
				<a href="{% url 'event-list' %}">Clear search</a>
			</div>
		</div>
		{% endif %}
	</div>
	{% if event_list %}
	  	<!-- Container to hold entire list of events. -->
	  	<div class="container"> 
	  		{% for event in event_list %}
	  			<!-- Each 'row' holds a container which in turn holds an event. -->
	  			<div class="row my-2">
	  				<!-- Individual Event container -->
	  				<div class="col">
		  				<div class="container border" onclick="location.href='{{ event.get_absolute_url }}'">
		  					<!-- First row of event container holds the event title and link. -->
		  					<div class="row flex-nowrap">
		  						<div class="col-8">
		  							<h5>{{ event.title }}</h5>
		  						</div>
		  						<div class="col">
									<span class="{% if event.status == 'o' %}text-success{% elif event.status == 'c' %}text-danger{% else %}text-warning{% endif %} float-right">{{ event.get_status_display }}</span>
								</div>
		  					</div>
		  					<!-- Second row contains organizer and sport -->
		  					<div class="row">
		  						<div class="col-8">
		  							<strong>Organizer: </strong>{{ event.organizer }}
		  						</div>
		  						<div class="col">
		  							<span class="float-right"><strong>Activity: </strong>{{ event.sport }}</span>
		  						</div>
		  					</div>
		  					<!-- Third holds date and time -->
		  					<div class="row">
		  						<div class="col">
		  							<strong>Time: </strong>{{ event.datetime }}
		  						</div>
		  					</div>
		  					<!-- Fourth row holds location -->
		  					<div class="row">
		  						<div class="col">
		  							<strong>Location: </strong>{{ event.location }}
		  						</div>
		  					</div>
		  					<!-- Fifth row holds details -->
		  					<div class="row">
		  						<div class="col">
		  							<strong>Details: </strong>{{ event.details|truncatechars:50 }}
		  						</div>
		  					</div>
		  					<!-- Sixth and final row holds how many positions are available -->
		  					<div class="row">
		  						<div class="col">
		  							<strong>Positions Available:</strong> {{ event.total_slots }}
		  						</div>
		  					</div>
		  				</div>
	  				</div>
	  			</div>
			{% endfor %}
		</div>
	{% else %}
		<div class="container my-2">
			<div class="row">
				<div class="col">
					<h5>There are no events scheduled.</h5>
				</div>
			</div>
		</div>
	{% endif %}
{% endblock %}

schedule/templates/schedule/event_status_update.html
{% extends "base.html" %}

{% block content %}

	<div class="container my-2">
		<div class="row">
			<div class="col">
				{% if event.status == 'o' %}
					<h5>Do you want to cancel this event?</h5>
				{% elif event.status == 'c' %}
					<h5>Do you want to reopen this event?</h5>
				{% endif %}
			</div>
		</div>
		<div class="row">
			<div class="col">
				<strong>{{ event }}</strong>
			</div>
		</div>
	</div>	
	<div class="container my-2">
		<div class="row">
			<div class="col">
				<form action="" method="POST">
					{% csrf_token %}
					{% if event.status == 'o' %}
						<input type="submit" value="Cancel Event" class="btn btn-primary btn-danger btn-block">
					{% elif event.status == 'c' %}
						<input type="submit" value="Reopen Event" class="btn btn-success btn-block">
					{% endif %}
				</form>
			</div>
		</div>
		<div class="row my-2">
			<div class="col">
				<a href="{{ event.get_absolute_url }}" class="btn btn-secondary btn-block">Go Back</a>
			</div>
		</div>
	</div>
{% endblock %}

schedule/templates/schedule/event_update_form.html
{% extends "base.html" %}

{% block content%}

	{{ form.media }}

	<div class="container">
		<div class="row my-2">
			<div class="col">
				<h2>Update Your Event - {{ event.title }}</h2>
			</div>
		</div>
	</div>

	<div class = "container">
		<form action="" method="post"> {% csrf_token %}
			{{ form.non_field_errors }}
			<div class="form-group">
				<label for="{{ form.title.id_for_label }}">Event Title<span class="req">*</span></label>
				{{ form.title }}
				{{ form.title.errors }}
			</div>
				<div class="form-group">
				<label for="{{ form.sport.id_for_label }}">Sport/Activity<span class="req">*</span></label>
				{{ form.sport }}
				{{ form.sport.errors }}
			</div>
			<div class="form-group">
				<label for="{{ form.datetime.id_for_label }}">Time<span class="req">*</span></label>
				{{ form.datetime }}
				{{ form.datetime.errors }}
			</div>
			<div class="form-group">
				<label for="{{ form.location.id_for_label }}">Location<span class="req">*</span></label>
				{{ form.location }}
				{{ form.location.errors }}
			</div>
			<div class="form-group">
				<label for="{{ form.details.id_for_label }}">Details</label>
				{{ form.details }}
				{{ form.details.errors }}
			</div>
			<input type="submit" value="Update" class="btn btn-primary btn-block my-2">
		</form>
		<a href="{{ event.get_absolute_url }}" class="btn btn-secondary btn-block my-2">Go Back</a>
		<a href="{% url 'event-slots-update' event.id %}" class="btn btn-info btn-block my-2">Update the Number of Needed Positions</a>
		{% if event.status == 'c' %}
			<a href="{% url 'event-status-update' event.pk %}" class="btn btn-primary btn-success btn-block my-2">Reopen Event</a>
		{% else %}
			<a href="{% url 'event-status-update' event.pk %}" class="btn btn-danger btn-block my-2">Cancel Event</a>
		{% endif %}
		</a>
	</div>
{% endblock %}

schedule/templates/schedule/myevents.html
{% extends "base.html" %}

{% block content %}
<div class="container my-2">
	<div class="row">
		<div class="col">
			<h5>Your Organized Events</h5>
		</div>
	</div>
	{% if events %}
		<table class="table table-hover">
			<tbody>
				{% for event in events %}
					<tr class="clickable-row" data-url="{{ event.get_absolute_url }}">
						<th scope="row" style="width: 40%">{{ event.title }}</th>
						<td style="width: 40%">{{ event.datetime }}</td>
						<td style="width: 20%" class="{% if event.status == 'o' %}text-success{% elif event.status == 'c' %}text-danger{% else %}text-warning{% endif %}">{{ event.get_status_display }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		<div class="row">
			<div class="col">
				You have no events scheduled.
			</div>
		</div>
	{% endif %}
</div>

<div class="container my-2">
	<div class="row">
		<div class="col">
			<h5>Events You Are Attending</h5>
		</div>
	</div>
	{% if slots %}
		<table class="table table-hover">
			<tbody>
				{% for slot in slots %}
					<tr class="clickable-row" data-url="{{ slot.event.get_absolute_url }}">
						<th scope="row" style="width: 40%">{{ slot.event.title }}</th>
						<td style="width: 40%">{{ slot.event.datetime }}</td>
						<td style="width: 20%" class="{% if slot.event.status == 'o' %}text-success{% elif slot.event.status == 'c' %}text-danger{% else %}text-warning{% endif %}">{{ slot.event.get_status_display }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		<div class="row">
			<div class="col">
				You are not attending any events.
			</div>
		</div>
	{% endif %}
</div>

<script>
	jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.location = $(this).data("url");
    });
});
</script>


{% endblock %}

schedule/templates/schedule/slot_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container my-2">
	<div class="row">
		<div class="col">
			<h5>Are you sure you want to delete this position from {{ slot.event }}?</h5>
		</div>
	</div>
</div>
<div class="container my-2">
	<div class="row">
		<div class="col">
			<form action="" method="POST">
				{% csrf_token %}
				<input type="submit" value="Remove Position" class="btn btn-danger btn-block">
			</form>
		</div>
	</div>
	<div class="row my-2">
		<div class="col">
			<a href="{% url 'event-slots-update' slot.event.pk %}" class="btn btn-secondary btn-block">Go Back</a>
		</div>
	</div>
</div>
{% endblock %}